### PR TITLE
bind crate to both `_local_` and `_site_`

### PR DESCRIPTION
**Pull request by chaudum**

### CODE REVIEW

**Comment by chaudum** [comment]
No, `_site_` is for all site-local addresses (e.g. 192.168.0.x, 10.0.1.x, ...),  `_local_` is only for the loopback interface (127.0.0.1)

**Comment by mxm** [comment]
I guess I'm missing context here. We need this to allow local connections within the container?

**Comment by mfussenegger** [comment]
> I guess I'm missing context here. We need this to allow local connections within the container for hba?

Would be nice if we could add the reasons for the change to the commit message

**Comment by mxm** [comment]
👍

**Pull request merged**
