### PR TITLE
Add examples on how to run docker-compose, as well as individual dock…

### PR DESCRIPTION
**Pull request by marregui**
…er containers

Why loose this information when it can be handy, conveniently waiting in a folder, rather
than having to copy code from the guide.

## Checklist

 - [ ] [CLA](https://crate.io/community/contribute/cla/) is signed

### CODE REVIEW

**Comment by seut** [comment]
Adding such stuff here will add another section we have to monitor and test on every major release which contains possible breaking changes.
Can't we link to the guide instead?

**Comment by marregui** [comment]
Do you mean moving the examples folder to the guide repo and then mentioning that there are examples under the examples folder of guide?, and then possibly taking the EXAMPLES file and merging it?

**Comment by seut** [comment]
@marregui Aren't all examples already mentioned at the guide, specially with your additions by https://github.com/crate/guide/pull/152? Do we really need more? As said, we have to maintain it.

> and then possibly taking the EXAMPLES file and merging it?

Which EXAMPLES file?

**Comment by marregui** [comment]
I suppose the guide already contains all the info, and you are right, the risk of the examples getting stale is there. 

I meant:

```examples/README.md``` 

I will proceed to close this request.

**Pull request closed without merging**
